
CREATE TABLE IF NOT EXISTS `mahasiswa` (
  `id_mahasiswa` int(225) NOT NULL auto_increment,
  `nim` varchar(50) NOT NULL,
  `nama` varchar(50) NOT NULL,
  `jk` varchar(50) NOT NULL,
  `status_nikah` varchar(50) NOT NULL,
  `tempat_lahir` varchar(50) NOT NULL,
  `tgl_lahir` date NOT NULL,
  `asal_propinsi` varchar(50) NOT NULL,
  `asal_kab/kota` varchar(50) NOT NULL,
  `kewarganegaraan` varchar(50) NOT NULL,
  `no_telp/hp` varchar(50) NOT NULL,
  `id_jurusan` int(225) NOT NULL,
  `id_prodi` int(225) NOT NULL,
  `sekolah_asal` varchar(50) NOT NULL,
  `jenis_sekolah` varchar(50) NOT NULL,
  `alamat_sekolah` varchar(50) NOT NULL,
  `kab/kota` varchar(50) NOT NULL,
  `nama_sekolah` varchar(50) NOT NULL,
  `thn_lulus` year(4) NOT NULL,
  `jurusan` varchar(50) NOT NULL,
  `nilai_ijazah` varchar(50) NOT NULL,
  `jumlah_mapel` varchar(50) NOT NULL,
  `nama_ayah` varchar(50) NOT NULL,
  `nama_ibu` varchar(50) NOT NULL,
  `alamat_ortu` varchar(50) NOT NULL,
  `propinsi` varchar(50) NOT NULL,
  `kab/kota_ortu` varchar(50) NOT NULL,
  `kd_pos` varchar(25) NOT NULL,
  `telp/hp_ortu` varchar(50) NOT NULL,
  `pekerjaan` varchar(50) NOT NULL,
  `pendidikan_ayah` varchar(50) NOT NULL,
  `penghasilan` varchar(50) NOT NULL,
  `photo` varchar(50) NOT NULL,
  PRIMARY KEY  (`id_mahasiswa`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


